language: node_js
node_js:
  - "6"
install:
  - cd ..
  - git init
  - git remote add origin https://github.com/eigenmethod/mam.git
  - git pull origin master
  - npm install
script:
  - npm start mol
  - node mol/-/node.test.js mol
